services:
    web:
        image: nginx:1.25.2-alpine
        container_name: ${COMPOSE_PROJECT_NAME}-web
        ports:
            - "80:80"
        volumes:
            - ./app/public:/app/public:ro
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - internal-network
    php:
        build:
            context: ./
            target: app_php_dev
            args:
                APP_UID: ${UID:-1000}
                APP_GID: ${GID:-1000}
        container_name: ${COMPOSE_PROJECT_NAME}-php
        volumes:
            - ./app:/app
        environment:
            XDEBUG_MODE: develop
            XDEBUG_SESSION: phpstorm
            SYMFONY_VERSION: ${SYMFONY_VERSION-stable}
        networks:
            - internal-network
    mysql:
        image: mysql:8.0
        container_name: ${COMPOSE_PROJECT_NAME}-mysql
        user: "${UID:-1000}:${GID:-1000}"
        environment:
            MYSQL_ROOT_PASSWORD: truc
            MYSQL_DATABASE: book
            MYSQL_USER: book
            MYSQL_PASSWORD: book1
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - internal-network
networks:
    internal-network:
        driver: bridge
        name: ${COMPOSE_PROJECT_NAME}-network
